# CommunityAnalytics
# Track your community to growth
# communityanalytics.net

# Platform 
platform_id: YOUR_SERVER_ID
platform_token: YOUR_SERVER_TOKEN

# You can enable this (when testing) to get extra insights.
debug: false

# The minimum duration (seconds) that a player must play for
# in order to be counted. This is useful to prevent players logging
# in and out (e.g. a hub) being treated as a player.
minimum-session-duration: 30