name: CommunityAnalytics
author: FNetwork
main: net.communityanalytics.spigot.SpigotPlugin
website: https://communityanalytics.net
version: 1.0.8
api-version: 1.13
commands:
  communityanalytics:
    permission: "communityanalytics.admin"
    permission-message: "You don't have permission for this command."
    description: "Reload, Debug and more..."
    usage: "/communityanalytics <reload|setup|help> "
    aliases:
      - "ca"
      - "community"
      - "analytics"
